name: CI/CD static site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Verificar que existe index.html (CI)
        run: test -f index.html

      - name: Despliegue continuo a otra rama (CD)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
